import { NgModule } from '@angular/core';
import {
    TuiButtonModule,
    TuiDataListModule,
    TuiHintModule,
    TuiModeModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSvgModule,
    TuiTextfieldControllerModule,
} from '@taiga-ui/core';
import {
    TuiBadgeModule,
    TuiDataListWrapperModule,
    TuiInputModule,
    TuiInputTagModule,
    TuiIslandModule,
    TuiLineClampModule,
    TuiMultiSelectModule,
    TuiTagModule,
    TuiTilesModule,
} from '@taiga-ui/kit';
import { TuiLetModule, TuiValueChangesModule } from '@taiga-ui/cdk';
import { TuiRippleModule } from '@taiga-ui/addon-mobile';
@NgModule({
    imports: [
        TuiSvgModule,
        TuiInputModule,
        TuiHintModule,
        TuiTextfieldControllerModule,
        TuiModeModule,
        TuiButtonModule,
        TuiInputTagModule,
        TuiTagModule,
        TuiScrollbarModule,
        TuiBadgeModule,
        TuiValueChangesModule,
        TuiMultiSelectModule,
        TuiLetModule,
        TuiDataListWrapperModule,
        TuiDataListModule,
        TuiRippleModule,
        TuiTilesModule,
        TuiRootModule,
        TuiIslandModule,
        TuiLineClampModule,
    ],
    exports: [
        TuiSvgModule,
        TuiInputModule,
        TuiHintModule,
        TuiTextfieldControllerModule,
        TuiModeModule,
        TuiButtonModule,
        TuiInputTagModule,
        TuiTagModule,
        TuiScrollbarModule,
        TuiBadgeModule,
        TuiValueChangesModule,
        TuiMultiSelectModule,
        TuiLetModule,
        TuiDataListWrapperModule,
        TuiDataListModule,
        TuiRippleModule,
        TuiTilesModule,
        TuiRootModule,
        TuiIslandModule,
        TuiLineClampModule,
    ],
})
export class TaigaModule {}
